@startuml architecture 

package "main" {
    class Bootstrap
}

package "core" {

    interface DataSink {
        +write(records: List<dict>)
    }

    interface PipelineService {
        +execute(raw_data: List<any>)
    }

    class TransformationEngine {
        -sink: DataSink
        +execute(raw_data)
    }

    TransformationEngine ..|> PipelineService
    TransformationEngine --> DataSink
}

package "plugins.inputs" {

    class CsvReader {
        -service: PipelineService
        +read(file)
    }

    class JSONReader {
        -service: PipelineService
        +read(file)
    }

    CsvReader --> PipelineService
    JSONReader --> PipelineService
}

package "plugins.outputs" {

    class ConsoleWriter {
        +write(records)
    }

    class GraphicsChartWriter {
        -chart_type: str
        +write(records)
    }

    ConsoleWriter ..|> DataSink
    GraphicsChartWriter ..|> DataSink
}

Bootstrap --> TransformationEngine
Bootstrap --> CsvReader
Bootstrap --> JSONReader
Bootstrap --> ConsoleWriter
Bootstrap --> GraphicsChartWriter


@enduml